In [218]:
import stribor as st
import torch
import iisignature 
import numpy as np
import os
from nfsde.experiments.synthetic.data import get_data_loaders
from nfsde.modules.flow_mc import FlowMC
from nfsde.modules.ctfp import CTFPModule
from nfsde.modules.flow_mc_z import FlowMCZ
from nfsde.modules.lsde import LSDE
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
DATA_DIR = 'nfsde/experiments/data/synth/'
name = 'ou' + '.npz'
loader = dict(np.load(DATA_DIR + name, allow_pickle=True))
ts = loader['time']
init = loader['init']
seq = loader['seq']
lsde

In [220]:
data_loader = get_data_loaders('ou', batch_size=20)
# mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/ou/20220815-182648/lightning_logs/version_7162391/checkpoints/last.ckpt", data=data_loader)
# mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/ou/20220815-182650/lightning_logs/version_7162389/checkpoints/last.ckpt", data=data_loader)
# mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/ou/20220815-182650/lightning_logs/version_7162390/checkpoints/last.ckpt", data=data_loader)
# mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/ou/20220815-182651/lightning_logs/version_7162392/checkpoints/last.ckpt", data=data_loader)
# mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/ou/20220815-184412/lightning_logs/version_7162394/checkpoints/last.ckpt", data=data_loader)
# mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/ou/20220815-184545/lightning_logs/version_7162395/checkpoints/last.ckpt", data=data_loader)
# mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/ou/20220815-184825/lightning_logs/version_7162396/checkpoints/last.ckpt", data=data_loader)
# mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/ou/20220815-204351/lightning_logs/version_7162499/checkpoints/last.ckpt", data=data_loader)
# mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/ou/20220815-204351/lightning_logs/version_7162450/checkpoints/last.ckpt", data=data_loader)
# mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/ou/20220815-204351/lightning_logs/version_7162451/checkpoints/last.ckpt", data=data_loader)
# mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/ou/20220815-204351/lightning_logs/version_7162452/checkpoints/last.ckpt", data=data_loader)
# mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/ou/20220815-204411/lightning_logs/version_7162503/checkpoints/last.ckpt", data=data_loader)
# mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/ou/20220815-205721/lightning_logs/version_7162506/checkpoints/last.ckpt", data=data_loader)
# mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/ou/20220815-210014/lightning_logs/version_7162508/checkpoints/last.ckpt", data=data_loader)
# mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/ou/20220815-210302/lightning_logs/version_7162498/checkpoints/last.ckpt", data=data_loader)
# mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/ou/20220815-185111/lightning_logs/version_7162388/checkpoints/last.ckpt", data=data_loader)

mc_module = LSDE.load_from_checkpoint("nfsde/result/download/test11/20220815-213124/lightning_logs/version_7162510/checkpoints/last.ckpt", data=data_loader)

# ctfp_module = ctfp_module = CTFPModule.load_from_checkpoint("nfsde/result/download/ctfp/20220614-173411/lightning_logs/version_6999089/checkpoints/last.ckpt", data=data_loader)

C:\Users\user\Anaconda3\envs\neuralf\lib\site-packages\torch\nn\init.py:403: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")


RuntimeError: Error(s) in loading state_dict for LSDE:
	Missing key(s) in state_dict: "model.pz0_mean", "model.pz0_logstd", "model.encoder._initial.weight", "model.encoder._initial.bias", "model.encoder._func._module.net.0.weight", "model.encoder._func._module.net.0.bias", "model.encoder._func._module.net.2.weight", "model.encoder._func._module.net.2.bias", "model.encoder._func._module.net.4.weight", "model.encoder._func._module.net.4.bias", "model.qz0_net.weight", "model.qz0_net.bias", "model.f_net.net.0.weight", "model.f_net.net.0.bias", "model.f_net.net.2.weight", "model.f_net.net.2.bias", "model.f_net.net.4.weight", "model.f_net.net.4.bias", "model.h_net.net.0.weight", "model.h_net.net.0.bias", "model.h_net.net.2.weight", "model.h_net.net.2.bias", "model.h_net.net.4.weight", "model.h_net.net.4.bias", "model.g_nets.0.net.0.weight", "model.g_nets.0.net.0.bias", "model.g_nets.0.net.2.weight", "model.g_nets.0.net.2.bias", "model.g_nets.1.net.0.weight", "model.g_nets.1.net.0.bias", "model.g_nets.1.net.2.weight", "model.g_nets.1.net.2.bias", "model.g_nets.2.net.0.weight", "model.g_nets.2.net.0.bias", "model.g_nets.2.net.2.weight", "model.g_nets.2.net.2.bias", "model.g_nets.3.net.0.weight", "model.g_nets.3.net.0.bias", "model.g_nets.3.net.2.weight", "model.g_nets.3.net.2.bias", "model.g_nets.4.net.0.weight", "model.g_nets.4.net.0.bias", "model.g_nets.4.net.2.weight", "model.g_nets.4.net.2.bias", "model.g_nets.5.net.0.weight", "model.g_nets.5.net.0.bias", "model.g_nets.5.net.2.weight", "model.g_nets.5.net.2.bias", "model.g_nets.6.net.0.weight", "model.g_nets.6.net.0.bias", "model.g_nets.6.net.2.weight", "model.g_nets.6.net.2.bias", "model.g_nets.7.net.0.weight", "model.g_nets.7.net.0.bias", "model.g_nets.7.net.2.weight", "model.g_nets.7.net.2.bias", "model.g_nets.8.net.0.weight", "model.g_nets.8.net.0.bias", "model.g_nets.8.net.2.weight", "model.g_nets.8.net.2.bias", "model.g_nets.9.net.0.weight", "model.g_nets.9.net.0.bias", "model.g_nets.9.net.2.weight", "model.g_nets.9.net.2.bias", "model.g_nets.10.net.0.weight", "model.g_nets.10.net.0.bias", "model.g_nets.10.net.2.weight", "model.g_nets.10.net.2.bias", "model.g_nets.11.net.0.weight", "model.g_nets.11.net.0.bias", "model.g_nets.11.net.2.weight", "model.g_nets.11.net.2.bias", "model.g_nets.12.net.0.weight", "model.g_nets.12.net.0.bias", "model.g_nets.12.net.2.weight", "model.g_nets.12.net.2.bias", "model.g_nets.13.net.0.weight", "model.g_nets.13.net.0.bias", "model.g_nets.13.net.2.weight", "model.g_nets.13.net.2.bias", "model.g_nets.14.net.0.weight", "model.g_nets.14.net.0.bias", "model.g_nets.14.net.2.weight", "model.g_nets.14.net.2.bias", "model.g_nets.15.net.0.weight", "model.g_nets.15.net.0.bias", "model.g_nets.15.net.2.weight", "model.g_nets.15.net.2.bias", "model.projector.weight", "model.projector.bias", "qy0_network.weight", "qy0_network.bias". 
	Unexpected key(s) in state_dict: "initial_encoder.encoder._initial.weight", "initial_encoder.encoder._initial.bias", "initial_encoder.encoder._func._module.net.0.weight", "initial_encoder.encoder._func._module.net.0.bias", "initial_encoder.encoder._func._module.net.2.weight", "initial_encoder.encoder._func._module.net.2.bias", "initial_encoder.encoder._func._module.net.4.weight", "initial_encoder.encoder._func._module.net.4.bias", "initial_encoder.z0_net.weight", "initial_encoder.z0_net.bias", "initial_encoder.z_all_net.weight", "initial_encoder.z_all_net.bias", "model.flow.transforms.0.latent_net.net.0.weight", "model.flow.transforms.0.latent_net.net.0.bias", "model.flow.transforms.0.latent_net.net.2.weight", "model.flow.transforms.0.latent_net.net.2.bias", "model.flow.transforms.0.latent_net.net.4.weight", "model.flow.transforms.0.latent_net.net.4.bias", "model.flow.transforms.0.time_net.shift", "model.flow.transforms.0.time_net.weight", "model.flow.transforms.1.latent_net.net.0.weight", "model.flow.transforms.1.latent_net.net.0.bias", "model.flow.transforms.1.latent_net.net.2.weight", "model.flow.transforms.1.latent_net.net.2.bias", "model.flow.transforms.1.latent_net.net.4.weight", "model.flow.transforms.1.latent_net.net.4.bias", "model.flow.transforms.1.time_net.shift", "model.flow.transforms.1.time_net.weight", "model.flow.transforms.2.latent_net.net.0.weight", "model.flow.transforms.2.latent_net.net.0.bias", "model.flow.transforms.2.latent_net.net.2.weight", "model.flow.transforms.2.latent_net.net.2.bias", "model.flow.transforms.2.latent_net.net.4.weight", "model.flow.transforms.2.latent_net.net.4.bias", "model.flow.transforms.2.time_net.shift", "model.flow.transforms.2.time_net.weight", "model.flow.transforms.3.latent_net.net.0.weight", "model.flow.transforms.3.latent_net.net.0.bias", "model.flow.transforms.3.latent_net.net.2.weight", "model.flow.transforms.3.latent_net.net.2.bias", "model.flow.transforms.3.latent_net.net.4.weight", "model.flow.transforms.3.latent_net.net.4.bias", "model.flow.transforms.3.time_net.shift", "model.flow.transforms.3.time_net.weight". 
	size mismatch for readout.weight: copying a param with shape torch.Size([3, 16]) from checkpoint, the shape in current model is torch.Size([1, 16]).
	size mismatch for readout.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([1]).

In [242]:
data_loader = get_data_loaders('lorenz', batch_size=50)
mc_module = FlowMC.load_from_checkpoint("nfsde/result/download/test11/20220815-220343/lightning_logs/version_7162580/checkpoints/last.ckpt", data=data_loader)

In [243]:
num_levels = 5
_, _, dl_train, dl_val, dl_test, mean, std , *_ = data_loader
# esig.is_library_loaded()

In [244]:
mmd=[]
s1 = None
s2 = None
num_sample = 0.
num_data = 0.
for batch in dl_test:
    x, t, y_true = batch
    t_detach, y_true_detach = t.detach().cpu().numpy(), y_true.detach().cpu()
    for i in range(50):
        num_sample += x.shape[0]
        y = mc_module(t) #* std + mean
        y = y.detach().cpu().numpy()
        streams = np.concatenate([t_detach, y], axis=-1)
        sig_model = np.asarray([iisignature.sig(s, num_levels) for s in streams]).sum(axis=0)
        if s1 is None:
            s1 = sig_model
        else:
            s1 += sig_model
                        
    
    num_data += x.shape[0]
    streams2 = np.concatenate([t_detach, y_true_detach], axis=-1)

    sig_true = np.asarray([iisignature.sig(s, num_levels) for s in streams2]).sum(axis=0)
    if s2 is None:
        s2 = sig_true
    else:
        s2 += sig_true
        

np.sum((s1 / num_sample - s2 / num_data) ** 2)

155.65086278914248

In [245]:
t

tensor([[[0.0000],
         [0.0200],
         [0.0400],
         ...,
         [0.9600],
         [0.9800],
         [1.0000]],

        [[0.0000],
         [0.0200],
         [0.0400],
         ...,
         [0.9600],
         [0.9800],
         [1.0000]],

        [[0.0000],
         [0.0200],
         [0.0400],
         ...,
         [0.9600],
         [0.9800],
         [1.0000]],

        ...,

        [[0.0000],
         [0.0200],
         [0.0400],
         ...,
         [0.9600],
         [0.9800],
         [1.0000]],

        [[0.0000],
         [0.0200],
         [0.0400],
         ...,
         [0.9600],
         [0.9800],
         [1.0000]],

        [[0.0000],
         [0.0200],
         [0.0400],
         ...,
         [0.9600],
         [0.9800],
         [1.0000]]])

In [224]:
mmd=[]
s1 = None
s2 = None
num_sample = 0.
num_data = 0.
for batch in dl_train:
    x, t, y_true = batch
    t_detach, y_true_detach = t.detach().cpu().numpy(), y_true.detach().cpu()
    for i in range(50):
        print(i)
        num_sample += x.shape[0]
        y = mc_module(t[0].flatten(), x.shape[0]) #* std + mean
        y = y.detach().cpu().numpy()
        streams = np.concatenate([t_detach, y], axis=-1)
        sig_model = np.asarray([iisignature.sig(s, num_levels) for s in streams]).sum(axis=0)
        if s1 is None:
            s1 = sig_model
        else:
            s1 += sig_model
            
    
    num_data += x.shape[0]
    streams2 = np.concatenate([t_detach, y_true_detach], axis=-1)

    sig_true = np.asarray([iisignature.sig(s, num_levels) for s in streams2]).sum(axis=0)
    if s2 is None:
        s2 = sig_true
    else:
        s2 += sig_true

np.sum((s1 / num_sample - s2 / num_data) ** 2)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
0
1
2
3
4
5
6
7
8
9


KeyboardInterrupt: 

In [225]:
np.sum((s1 / num_sample - s2 / num_data) ** 2)

0.5796150975262981

In [90]:
mmd=[]
s1 = None
s2 = None
for batch in dl_train:
    x, t, y_true = batch
    y = ctfp_module( t) #* std + mean
    y_true = y_true#* std + mean
    t, y, y_true = t.detach().cpu().numpy(), y.detach().cpu().numpy(), y_true.detach().cpu()
    streams = np.concatenate([t, y], axis=-1)
    # print(streams)
    sig_model = np.asarray([iisignature.sig(s, num_levels) for s in streams]).mean(axis=0)
    # print(sig_model)
    streams2 = np.concatenate([t, y_true], axis=-1)
    # print(streams2)
    sig_true = np.asarray([iisignature.sig(s, num_levels) for s in streams2]).mean(axis=0)
    # print(sig_true)
    mmd.append(sig_model - sig_true)
    # print(sig_model - sig_true)

# print(mmd)
mmd = np.mean(mmd, axis=0)
np.sum(mmd**2)

NameError: name 'ctfp_module' is not defined

In [146]:
y = 0
for i in range(5):
    t = torch.linspace(0, 10, 101).view(1,-1,1).repeat_interleave(100, dim=0)
    ws = sample_brownian(t)
    y += f(ws, t) / 100
y / 5

tensor([[[-0.0003],
         [ 0.0021],
         [ 0.0005],
         ...,
         [ 0.0053],
         [ 0.0075],
         [ 0.0072]],

        [[-0.0003],
         [-0.0021],
         [-0.0032],
         ...,
         [-0.0240],
         [-0.0232],
         [-0.0231]],

        [[-0.0003],
         [-0.0046],
         [-0.0020],
         ...,
         [-0.0301],
         [-0.0296],
         [-0.0285]],

        ...,

        [[-0.0003],
         [ 0.0014],
         [ 0.0025],
         ...,
         [-0.0170],
         [-0.0173],
         [-0.0166]],

        [[-0.0003],
         [ 0.0015],
         [ 0.0005],
         ...,
         [ 0.0081],
         [ 0.0100],
         [ 0.0093]],

        [[-0.0003],
         [-0.0018],
         [-0.0005],
         ...,
         [ 0.0082],
         [ 0.0091],
         [ 0.0105]]], grad_fn=<DivBackward0>)

In [47]:
g = LatentCouplingFlow(1,1,4,[64]*2, 'TimeFourierBounded', 8)
g.load_state_dict(torch.load(os.getcwd()+'/nfsde/result/model.pt'))

<All keys matched successfully>

In [107]:
mmd = []
esig.is_library_loaded()
for batch in dl_test:
    x, t, y_true = batch
    ws = sample_brownian(t)
    y = g(x, ws, t)
    t, y, y_true = t.detach().cpu().numpy(), y.detach().cpu().numpy(), y_true.detach().cpu()
    streams = np.concatenate([t, y], axis=-1)
    sig_model = np.asarray([esig.tosig.stream2sig(s, num_levels) for s in streams]).mean(axis=0)
    streams2 = np.concatenate([t, y_true], axis=-1)
    sig_true = np.asarray([esig.tosig.stream2sig(s, num_levels) for s in streams2]).mean(axis=0)
    mmd.append(sig_model - sig_true)
mmd = np.mean(mmd, axis=0)
np.sum(mmd**2)
# mmd

9.843329160731395e+46

In [152]:
y = 0
x = torch.zeros(100, 1, 1)
for i in range(1):
    t = torch.linspace(0, 10, 101).view(1,-1,1).repeat_interleave(100, dim=0)
    ws = sample_brownian(t)
    y += g(x, ws, t).mean(0)
    print(g(x, ws, t))
    break
y / 5

tensor([[[ 0.0000],
         [ 0.1344],
         [ 0.4758],
         ...,
         [-0.4300],
         [-0.6819],
         [-0.2360]],

        [[ 0.0000],
         [ 3.2161],
         [ 1.4512],
         ...,
         [ 2.4921],
         [ 3.1058],
         [ 2.7891]],

        [[ 0.0000],
         [ 0.0119],
         [ 0.8310],
         ...,
         [ 3.6492],
         [ 2.1081],
         [ 1.1985]],

        ...,

        [[ 0.0000],
         [ 1.5002],
         [ 3.1224],
         ...,
         [ 1.1565],
         [ 3.4226],
         [ 3.8300]],

        [[ 0.0000],
         [ 1.2166],
         [ 0.2478],
         ...,
         [-1.4129],
         [-1.4455],
         [-1.3873]],

        [[ 0.0000],
         [ 3.6598],
         [ 5.1615],
         ...,
         [-1.3782],
         [-1.3145],
         [-1.2748]]], grad_fn=<AddBackward0>)


tensor([[ 0.0000],
        [ 0.0939],
        [ 0.1430],
        [ 0.1256],
        [ 0.1484],
        [ 0.2102],
        [ 0.2146],
        [ 0.2255],
        [ 0.2378],
        [ 0.1850],
        [ 0.1503],
        [ 0.0913],
        [ 0.1548],
        [ 0.1520],
        [ 0.0928],
        [ 0.1453],
        [ 0.1290],
        [ 0.1549],
        [ 0.0796],
        [ 0.1489],
        [ 0.1587],
        [ 0.2286],
        [ 0.2283],
        [ 0.2526],
        [ 0.2047],
        [ 0.2039],
        [ 0.1529],
        [ 0.2054],
        [ 0.1826],
        [ 0.1607],
        [ 0.1799],
        [ 0.1734],
        [ 0.1125],
        [ 0.1376],
        [ 0.0960],
        [ 0.0886],
        [ 0.0758],
        [ 0.0626],
        [ 0.0659],
        [ 0.0346],
        [ 0.0305],
        [ 0.0321],
        [ 0.0394],
        [ 0.0214],
        [ 0.0007],
        [ 0.0638],
        [ 0.0650],
        [ 0.1073],
        [ 0.0529],
        [ 0.0758],
        [ 0.0583],
        [ 0.0268],
        [ 0.